name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install the Packages
        shell: bash
        run: npx pnpm install

      - name: Update Sponsors
        shell: bash
        run: npm run build
        env:
          SPONSORKIT_GITHUB_LOGIN:    ${{ secrets.SPONSORKIT_GITHUB_LOGIN }}
          SPONSORKIT_GITHUB_TOKEN:    ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_AFDIAN_USER_ID:  ${{ secrets.SPONSORKIT_AFDIAN_USER_ID }}
          SPONSORKIT_AFDIAN_TOKEN:    ${{ secrets.SPONSORKIT_AFDIAN_TOKEN }}

      - name: Add and Commit the Changes
        id: acc
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: update sponsors.svg'
          add: './static/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Outputs of the Commit
        if: steps.acc.outputs.committed == 'true'
        shell: bash
        run: |
          echo "Commit's URL = ${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.acc.outputs.commit_long_sha }}"
          echo "Commit's SHA = ${{ steps.acc.outputs.commit_long_sha }}"
